/**
 * All chatbot prompt data and copy — single source of truth for the portfolio bot.
 * Responses are generated in portfolioBot.ts using this data.
 */

export const PORTFOLIO_INFO = {
  name: "Mukuka Nkamba",
  title:
    "Full Stack Software Engineer | AI & GenAI (RAG) Enthusiast | Data Analyst | Content Creator",
  contact: {
    phone: "+260 962 398 849",
    email: "mukukankambaa@gmail.com",
    linkedin: "https://www.linkedin.com/in/mukuka-nkamba-4a9b16290/",
    github: "https://github.com/nkamba-mukuka",
    tiktok: "https://www.tiktok.com/@mukukankamba",
  },
  bio: "Results-driven Full Stack Software Engineer with a strong track record of building scalable, cloud-native, and data-driven applications. Experienced across the full software development lifecycle, with expertise in React, Next.js, Node.js, Firebase, and GCP, and hands-on proficiency in Golang, PHP, PostgreSQL, TypeScript, and Python. Passionate about AI-powered systems (RAG), clean architecture, and collaborating with cross-functional Agile teams to deliver high-quality, user-centric products.",
  skills: {
    frontend: ["React", "Next.js", "JavaScript", "TypeScript", "HTML", "CSS"],
    backend: ["Node.js", "Golang", "PHP", "Python"],
    cloudDevOps: [
      "Firebase (Auth, Firestore, Cloud Functions)",
      "Google Cloud Platform",
      "CI/CD Pipelines",
    ],
    databases: ["PostgreSQL", "SQL"],
    tools: ["Git", "Postman", "Tableau", "Power BI", "Excel", "Google Sheets"],
    ai: [
      "Retrieval-Augmented Generation (RAG)",
      "Prompt Engineering",
      "Data Visualization",
      "Basic Machine Learning",
    ],
  },
  experience: [
    {
      role: "Peak Software Developer (Full Stack)",
      company: "Hytel",
      location: "Lusaka, Zambia",
      period: "Aug 2025 – Present",
      description:
        "Lead development of production-grade, cloud-based web apps (React, Next.js, Node.js, Firebase, GCP). Architect scalable frontends; build backend services with Firestore, Firebase Auth, Cloud Functions. Design CI/CD pipelines. Integrate GenAI and RAG into business workflows. Collaborate with international, cross-functional Agile teams.",
      tech: ["React", "Next.js", "Node.js", "Firebase", "GCP", "RAG", "CI/CD"],
    },
    {
      role: "Full Stack Developer",
      company: "Fin360",
      location: "Lusaka, Zambia",
      period: "May 2024 – Aug 2025",
      description:
        "Enterprise web apps with PHP (Yii2), JavaScript, HTML, CSS. Auth, RBAC, data reporting. RESTful APIs. SQL optimization.",
      tech: ["PHP", "Yii2", "JavaScript", "RESTful APIs"],
    },
    {
      role: "Junior Software Engineer",
      company: "Kuala Tech",
      location: "Lusaka, Zambia",
      period: "May 2024 – Feb 2025",
      description:
        "Backend APIs (Golang, PostgreSQL). Frontend components (React, Next.js, TypeScript). Performance tuning, testing, debugging. Sprint planning, code reviews, Postman API integration.",
      tech: ["Golang", "PostgreSQL", "React", "Next.js", "TypeScript"],
    },
    {
      role: "Junior Software Engineer Intern",
      company: "Cyprus Codes (Ata Bilişim)",
      location: "Cyprus",
      period: "Sept 2021 – Aug 2022",
      description:
        "Web interfaces with HTML, CSS, React, Angular. Frontend optimization, bug fixing, UI improvements. Daily stand-ups, sprint reviews, version control and deployment.",
      tech: ["HTML", "CSS", "React", "Angular"],
    },
  ],
  education: [
    {
      degree: "Bachelor of Science in Software Engineering",
      institution: "Cyprus International University",
      period: "2019 – 2024",
      note: "Graduated Spring 2023 as the only female in my department.",
    },
    {
      degree: "High School Certificate",
      institution: "Chipembi Girls Secondary School",
      period: "2014 – 2018",
    },
  ],
  certifications: [
    "HTML5 Certification — Enduonix Learning Solutions",
    "Backend Master Class (Golang, PostgreSQL, gRPC) — Udemy",
    "Tech4Dev WomenTechsters Data Analyst Program (Cohort 4)",
    "Hytel Software Development Bootcamp — 2025",
  ],
  projects: [
    {
      name: "Hytel Elixir",
      description:
        "Agile methodology system with intelligent project management, collaboration, and data-driven insights.",
      link: "https://elixir-98f15.web.app/",
      tech: ["Project Management", "AI", "Collaboration"],
    },
    {
      name: "Klapton Insurance Zambia (KIZ)",
      description:
        "Digital insurance for your home. Superior products and services for economic growth.",
      link: "https://kiz.co.zm/",
      tech: ["FinTech", "Zambia", "Digital Insurance"],
    },
  ],
  interests: [
    "AI Agents & Generative AI",
    "Cloud Architecture",
    "Clean Code & Software Design",
    "Technical Writing",
    "Community Tech Education",
    "Open-Source",
    "Product Design",
    "Women in Tech Advocacy",
    "Content Creation",
    "Mentorship",
    "Cooking",
    "Traveling",
    "Art",
    "Interior Design",
  ],
  personal: {
    cooking:
      "I love cooking. It's one of my favorite ways to unwind and get creative outside of code.",
    traveling:
      "I love traveling and hope to see the world one day. New places and cultures feed my curiosity.",
    art: "I love art—both appreciating it and the creative side of building products and interfaces.",
    reading: "I enjoy reading. It keeps me sharp and helps me think differently.",
    walks: "I like taking walks. Good for clearing my head and getting into a good headspace.",
    blog: "I run a blog where I share my thoughts and experiences—mostly around tech, growth, and the journey.",
    songOnRepeat: "Ice 2 Water by Waykins. I've had it on repeat lately.",
    morningRoutine:
      "I like to start my day with a warm drink—it helps me wake up and get into a positive mindset before work.",
    inspiration:
      "I'm inspired by fulfillment—doing meaningful work and growing personally and professionally.",
    funFact:
      "I run a blog where I share my thoughts and experiences. Also graduated as the only woman in my Software Engineering department at uni.",
  },
  music: {
    house: "I love house music in general.",
    afrocentric:
      "I love the afrocentric aspect of things—music, culture, design, and how it shows up in what I build and consume.",
  },
  hytel: {
    role: "I'm a Software Developer at Hytel.",
    typicalDay:
      "My typical day involves writing code, collaborating with my team, and working on projects that improve our products and processes.",
    enjoy: "I enjoy the friendliness and supportive culture of the team.",
    standsOut:
      "Hytel stands out for its focus on scalability and building solutions that can grow effectively over time.",
    bootcamp:
      "I did the Hytel AI Bootcamp (Africa Prime)—explored AI fundamentals, Generative AI, and RAG—then was hired. I contribute to meaningful, scalable projects in a dynamic, fast-paced environment.",
  },
  narrative:
    "I graduated from Cyprus International University (Spring 2023) as the only female in my department. Through internships at Cyprus Codes and Ata Bilişim I gained hands-on front-end experience in Agile teams. After the Hytel AI Bootcamp I was hired by Hytel; I also did the Tech4Dev WomenTechsters Data Analyst program to bridge software engineering with data insights. Beyond tech I'm a Content Creator and Women in Tech Advocate—sharing my journey, mentoring, and creating resources to empower women in STEM. I'm known for adaptability, curiosity, and problem-solving at the intersection of engineering, AI, and mentorship.",
  attributes: [
    "Good communication and interpersonal skills",
    "Ability to work independently and under pressure",
    "Strong character and discipline",
    "Creative and organized problem-solver",
    "Adaptability and curiosity",
  ],
} as const;

export const BARISTA_GREETINGS = [
  "Hey there, gorgeous! ☕✨",
  "Ouuu, welcome babe! What can I brew for you today?",
  "Hi beautiful! Ready to explore? Let's go! 💕",
  "Heyyy! So excited you're here! What's up? ☕",
];

export const TRIGGERS = {
  skills: [
    "skill",
    "what can you",
    "technolog",
    "tech stack",
    "language",
    "stack",
    "coding",
    "expertise",
    "proficient",
    "what are you good at",
    "what's your stack",
    "technologies",
    "programming stack",
  ],
  projects: [
    "project",
    "build",
    "portfolio",
    "made",
    "what have you built",
    "what did you make",
    "your work",
    "what projects",
    "what apps",
  ],
  about: [
    "about",
    "who",
    "bio",
    "yourself",
    "story",
    "identity",
    "tell me about",
    "who is mukuka",
    "what's your background",
  ],
  interests: [
    "interest",
    "hobby",
    "hobbies",
    "like",
    "fun",
    "passion",
    "what are you into",
    "what do you like",
    "what's your passion",
    "what do you do for fun",
    "cooking",
    "travel",
    "traveling",
    "art",
    "music",
    "reading",
    "walks",
    "blog",
    "fave",
    "fav",
    "favorite",
  ],
  personal: [
    "cooking",
    "cook",
    "travel",
    "traveling",
    "art",
    "reading",
    "walks",
    "walk",
    "blog",
    "fun fact",
    "hidden talent",
    "song on repeat",
    "currently loving",
    "on repeat",
    "start your day",
    "morning",
    "routine",
    "good mood",
    "warm drink",
    "inspires you",
    "inspiration",
    "typical day",
    "day in the life",
    "what do you enjoy",
    "hytel team",
    "hytel stand out",
    "waykins",
    "ice 2 water",
    "house music",
    "afrocentric",
    "music you like",
  ],
  genZSlang: [
    "vibe",
    "tea",
    "spill the tea",
    "no cap",
    "slay",
    "fire",
    "goals",
    "bestie",
    "lit",
    "mood",
    "same energy",
  ],
  hello: [
    "hello",
    "hi",
    "hey",
    "hai",
    "sup",
    "hii",
    "heyy",
    "hiya",
    "what's up",
    "whatsup",
    "wassup",
    "yo",
    "yoo",
    "what's good",
    "whats good",
    "wagwan",
    "what's poppin",
    "hey bestie",
    "hi bestie",
    "gm",
    "gn",
  ],
  contact: [
    "contact",
    "email",
    "reach",
    "phone",
    "talk",
    "social",
    "linkedin",
    "github",
    "get in touch",
    "connect",
  ],
  experience: [
    "experience",
    "work",
    "job",
    "career",
    "company",
    "where do you work",
    "what's your job",
    "current role",
    "work history",
    "what's your role",
  ],
  education: [
    "education",
    "degree",
    "university",
    "school",
    "graduate",
    "study",
    "where did you study",
    "what's your degree",
    "alma mater",
  ],
  certification: [
    "certification",
    "certificate",
    "cert",
    "credentials",
    "qualifications",
  ],
  availability: [
    "available",
    "hiring",
    "freelance",
    "consulting",
    "contract",
    "open to work",
    "are you available",
  ],
  rates: ["rate", "price", "cost", "charge", "how much", "pricing", "fee"],
  collaboration: [
    "collaborate",
    "work together",
    "team up",
    "can you help",
    "can you build",
    "looking to collaborate",
  ],
  mentorship: [
    "mentor",
    "mentorship",
    "teach",
    "advice",
    "guidance",
    "help me learn",
  ],
  location: [
    "where are you",
    "location",
    "where do you live",
    "based",
    "where are you from",
    "where you at",
  ],
  womenInTech: [
    "women in tech",
    "female engineer",
    "diversity",
    "only female",
    "women techsters",
    "advocacy",
  ],
  content: [
    "content",
    "tiktok",
    "create content",
    "content creator",
    "your content",
  ],
} as const;
